@startuml
title Activitate: Promovarea unui pion

start

:Execută mutare;

if (Pionul a ajuns pe ultima linie?) then (Da)
  :Blochează interacțiunea jocului;
  :Afișează dialog de promovare;
  :Utilizatorul selectează piesă (regină, cal, nebun, turn);

  :Înlocuiește pionul cu piesa aleasă;
  :Actualizează starea tablei;
else (Nu)
  :Continuă jocul;
endif

stop
@enduml
